In [1]:
import numpy as np

In [11]:
time = np.arange(0,1/30000*(179200),1/30000)

In [12]:
len(time)

179200

In [5]:
len(time)

1

In [6]:
len(time)

1

In [7]:
len(time.T)

1

In [14]:
a=np.array([0,1])

In [16]:
a.amax

AttributeError: 'numpy.ndarray' object has no attribute 'amax'

In [18]:
import collections as clt
Point = clt.namedtuple()

In [22]:
time = np.arange(0,1024/30000,1/30000)

In [23]:
len(time)

1024

In [24]:
time[1:3]

array([3.33333333e-05, 6.66666667e-05])

In [25]:
time[1:3].amax

AttributeError: 'numpy.ndarray' object has no attribute 'amax'

In [26]:
max(time[1:4])

0.0001

In [27]:
time[4:1]

array([], dtype=float64)

In [28]:
time[1:4:-1]

array([], dtype=float64)

In [29]:
time[1:4]

array([3.33333333e-05, 6.66666667e-05, 1.00000000e-04])

In [30]:
time[::-1]

array([3.41000000e-02, 3.40666667e-02, 3.40333333e-02, ...,
       6.66666667e-05, 3.33333333e-05, 0.00000000e+00])

In [31]:
time

array([0.00000000e+00, 3.33333333e-05, 6.66666667e-05, ...,
       3.40333333e-02, 3.40666667e-02, 3.41000000e-02])

In [32]:
time[4:1:-1]

array([1.33333333e-04, 1.00000000e-04, 6.66666667e-05])

In [34]:
a=np.array(([-1,2,3,4],[5,6,-7,8]),int)
absA=abs(a)
absA

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])